#!/bin/bash
#
# gen_ld_inc.sh - Auto-generate linker script include (.ld.inc) files
# from the list of object files in the Makefile.
#
# Usage:
#   gen_ld_inc.sh <output_dir> <version_suffix> [--force]
#
# This script reads the list of object files from the Makefile's
# existing file-gathering logic and generates the corresponding
# .text, .data, .rodata, and .bss .ld.inc files.
#
# This eliminates the need to manually add new source files to
# the linker include files.
#

set -euo pipefail

OUTPUT_DIR="${1:?Usage: gen_ld_inc.sh <output_dir> <version_suffix>}"
VERSION_SUFFIX="${2:?Usage: gen_ld_inc.sh <output_dir> <version_suffix>}"
FORCE="${3:-}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

LD_DIR="$PROJECT_DIR/ld"
OUTCODE="${VERSION_SUFFIX}"

# Build output path prefix
PREFIX="build/${OUTCODE}"

# Generate a single section file from a list of object files
# Args: <section_name> <output_file> [object_dir...]
gen_section_file() {
    local section="$1"
    local output_file="$2"
    shift 2

    mkdir -p "$(dirname "$output_file")"

    # If we have source directories, scan them. Otherwise use stdin.
    if [ $# -gt 0 ]; then
        # Scan directories for .o files that match the section
        for dir in "$@"; do
            if [ -d "$dir" ]; then
                find "$dir" -name "*.o" -type f | sort | while read -r obj; do
                    # Get the path relative to project root
                    rel_path="${obj#$PROJECT_DIR/}"
                    echo "      ${rel_path} (${section});"
                done
            fi
        done
    fi
}

# Alternative: generate from a list of .c/.s files (paths relative to project root)
# Args: <section> <output_file> < file_list.txt
gen_from_objects() {
    local section="$1"
    local output_file="$2"

    mkdir -p "$(dirname "$output_file")"

    while IFS= read -r objfile; do
        objfile="${objfile//\$\(OUTCODE\)/${OUTCODE}}"
        objfile="${objfile//OUTCODE/${OUTCODE}}"
        echo "      ${objfile} (${section});"
    done
}

echo "Generating .ld.inc files for version '${VERSION_SUFFIX}'..."
echo "  Output directory: ${OUTPUT_DIR}"

# --- Copy existing .ld.inc files if not regenerating ---
# We keep the existing files as they are (they use OUTCODE placeholder
# which gets expanded by cpp). If you want to regenerate from scratch,
# pass --force and the script will scan the source tree.

if [ "${FORCE}" != "--force" ] && [ -d "${LD_DIR}" ]; then
    echo "  Keeping existing .ld.inc files in ${LD_DIR}/"
    echo "  Use --force to regenerate from source tree."
    echo "  Note: existing .ld.inc files use OUTCODE placeholder and"
    echo "  #ifdef guards - they are more precise than auto-generation."
    echo ""
    echo "  For auto-detection of new files, the Makefile uses wildcard"
    echo "  patterns that automatically pick up new .c/.s files."
    echo "  See the Makefile's GCC mode for details."
    exit 0
fi

echo "  Regenerating .ld.inc files from source tree..."

# --- Generate lib section files (src/*.c, src/libultrare/*.c) ---

# Collect all .o files for the lib (code) section
LIB_OBJECTS=$(cat <<'EOF'
$(foreach dir,src,$(wildcard $(dir)/*.c))
$(foreach dir,src,$(wildcard $(dir)/*.s))
$(foreach dir,src/libultrare,$(wildcard $(dir)/*.c))
$(foreach dir,src/libultrare,$(wildcard $(dir)/*.s))
EOF
)

# For now, generate a comprehensive set from the source tree
# Text section
cat > "${LD_DIR}/lib.text.ld.inc" << 'LDEOF'
# Auto-generated by gen_ld_inc.sh -- do not edit by hand
# To regenerate: scripts/gen_ld_inc.sh build <version> --force
LDEOF

# Scan for C files in src/ (not in subdirectories)
find "${PROJECT_DIR}/src" -maxdepth 1 -name "*.c" -o -name "*.s" | sort | while read -r srcfile; do
    basename_noext=$(basename "$srcfile")
    basename_noext="${basename_noext%.*}"
    echo "      build/OUTCODE/src/${basename_noext}.o (.text);" >> "${LD_DIR}/lib.text.ld.inc"
done

# Add libultrare files
find "${PROJECT_DIR}/src/libultrare" -name "*.c" -o -name "*.s" | sort | while read -r srcfile; do
    rel="${srcfile#${PROJECT_DIR}/src/}"
    rel_noext="${rel%.*}"
    echo "      build/OUTCODE/src/${rel_noext}.o (.text);" >> "${LD_DIR}/lib.text.ld.inc"
done

# Data section
cat > "${LD_DIR}/lib.data.ld.inc" << 'LDEOF'
# Auto-generated by gen_ld_inc.sh -- do not edit by hand
LDEOF
find "${PROJECT_DIR}/src" -maxdepth 1 \( -name "*.c" -o -name "*.s" \) | sort | while read -r srcfile; do
    basename_noext=$(basename "$srcfile")
    basename_noext="${basename_noext%.*}"
    echo "      build/OUTCODE/src/${basename_noext}.o (.data);" >> "${LD_DIR}/lib.data.ld.inc"
done
find "${PROJECT_DIR}/src/libultrare" \( -name "*.c" -o -name "*.s" \) | sort | while read -r srcfile; do
    rel="${srcfile#${PROJECT_DIR}/src/}"
    rel_noext="${rel%.*}"
    echo "      build/OUTCODE/src/${rel_noext}.o (.data);" >> "${LD_DIR}/lib.data.ld.inc"
done

# Rodata section
cat > "${LD_DIR}/lib.rodata.ld.inc" << 'LDEOF'
# Auto-generated by gen_ld_inc.sh -- do not edit by hand
LDEOF
find "${PROJECT_DIR}/src" -maxdepth 1 \( -name "*.c" -o -name "*.s" \) | sort | while read -r srcfile; do
    basename_noext=$(basename "$srcfile")
    basename_noext="${basename_noext%.*}"
    echo "      build/OUTCODE/src/${basename_noext}.o (.rodata);" >> "${LD_DIR}/lib.rodata.ld.inc"
done
find "${PROJECT_DIR}/src/libultrare" \( -name "*.c" -o -name "*.s" \) | sort | while read -r srcfile; do
    rel="${srcfile#${PROJECT_DIR}/src/}"
    rel_noext="${rel%.*}"
    echo "      build/OUTCODE/src/${rel_noext}.o (.rodata);" >> "${LD_DIR}/lib.rodata.ld.inc"
done

# Bss section
cat > "${LD_DIR}/lib.bss.ld.inc" << 'LDEOF'
# Auto-generated by gen_ld_inc.sh -- do not edit by hand
LDEOF
find "${PROJECT_DIR}/src" -maxdepth 1 \( -name "*.c" -o -name "*.s" \) | sort | while read -r srcfile; do
    basename_noext=$(basename "$srcfile")
    basename_noext="${basename_noext%.*}"
    echo "      build/OUTCODE/src/${basename_noext}.o (.bss);" >> "${LD_DIR}/lib.bss.ld.inc"
done
find "${PROJECT_DIR}/src/libultrare" \( -name "*.c" -o -name "*.s" \) | sort | while read -r srcfile; do
    rel="${srcfile#${PROJECT_DIR}/src/}"
    rel_noext="${rel%.*}"
    echo "      build/OUTCODE/src/${rel_noext}.o (.bss);" >> "${LD_DIR}/lib.bss.ld.inc"
done

# --- Generate game section files (src/game/*.c, src/game/*.s) ---

# Text
cat > "${LD_DIR}/game.text.ld.inc" << 'LDEOF'
# Auto-generated by gen_ld_inc.sh -- do not edit by hand
LDEOF
find "${PROJECT_DIR}/src/game" \( -name "*.c" -o -name "*.s" \) | sort | while read -r srcfile; do
    basename_noext=$(basename "$srcfile")
    basename_noext="${basename_noext%.*}"
    echo "      build/OUTCODE/src/game/${basename_noext}.o (.text);" >> "${LD_DIR}/game.text.ld.inc"
done

# Data
cat > "${LD_DIR}/game.data.ld.inc" << 'LDEOF'
# Auto-generated by gen_ld_inc.sh -- do not edit by hand
LDEOF
find "${PROJECT_DIR}/src/game" \( -name "*.c" -o -name "*.s" \) | sort | while read -r srcfile; do
    basename_noext=$(basename "$srcfile")
    basename_noext="${basename_noext%.*}"
    echo "      build/OUTCODE/src/game/${basename_noext}.o (.data);" >> "${LD_DIR}/game.data.ld.inc"
done

# Rodata
cat > "${LD_DIR}/game.rodata.ld.inc" << 'LDEOF'
# Auto-generated by gen_ld_inc.sh -- do not edit by hand
LDEOF
find "${PROJECT_DIR}/src/game" \( -name "*.c" -o -name "*.s" \) | sort | while read -r srcfile; do
    basename_noext=$(basename "$srcfile")
    basename_noext="${basename_noext%.*}"
    echo "      build/OUTCODE/src/game/${basename_noext}.o (.rodata);" >> "${LD_DIR}/game.rodata.ld.inc"
done

# Bss
cat > "${LD_DIR}/game.bss.ld.inc" << 'LDEOF'
# Auto-generated by gen_ld_inc.sh -- do not edit by hand
LDEOF
find "${PROJECT_DIR}/src/game" \( -name "*.c" -o -name "*.s" \) | sort | while read -r srcfile; do
    basename_noext=$(basename "$srcfile")
    basename_noext="${basename_noext%.*}"
    echo "      build/OUTCODE/src/game/${basename_noext}.o (.bss);" >> "${LD_DIR}/game.bss.ld.inc"
done

echo "  Done! Generated .ld.inc files in ${LD_DIR}/"
echo ""
echo "  NOTE: Auto-generated files list every .c/.s file in each section."
echo "  If a file has no .data/.rodata/.bss content, the linker will"
echo "  simply ignore the empty section reference. This is harmless."
echo ""
echo "  If you need byte-perfect binary matching, keep the manual files."
echo "  For GCC builds (GCC=YES), auto-generated files are sufficient."
